***

# Descrition of sections of the run_analysis.R file.

***

## Part 1 - Creating a environment and getting files.

***

#### 1. Create work folders.
###### Verify if a folder strutucure exists. Create if not exists. 
```
if (!file.exists(paste0(getwd(),"/R1"))) {
   dir.create(paste0(getwd(),"/R1/coursera_gcd/workfolder/dataFiles"), recursive = TRUE);
}
```

#### 2. Go to files folder.
###### The data files will put in "dataFiles" folder and we setting workfolder to this path.
```
setwd("./coursera_gcd/workfolder/dataFiles");getwd()
```

#### 3. Download zip data file.
###### Getting the compressed file from Cloudfront and uncompress data files into workfolder.
```
url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
file <- "getdata-projectfiles-UCI HAR Dataset.zip"
download.file(url, file, mode="wb")
unzip(file, exdir = ".", overwrite = TRUE)
```

#### 4. Install packs e load libraries.
###### Install and load packages and libraries that we will use in this script.
```
install.packages("data.table")
library(data.table)

install.packages("dplyr")
library(dplyr)

install.packages("rmarkdown")
library(rmarkdown)
```

***

## Part 2 - Cleaning data.

***


#### 1. Merges the training and the test sets to create one data set.
+ Reading "Test" files and load in datasets.
```
testActivity <- read.table("./UCI HAR Dataset/test/Y_test.txt", header = FALSE)
testSubject <- read.table("./UCI HAR Dataset/test/subject_test.txt", header = FALSE)
testFeatures <- read.table("./UCI HAR Dataset/test/X_test.txt", header = FALSE)
```

+ Reading "Train" files and load in datasets.
```
trainActivity <- read.table("./UCI HAR Dataset/train/Y_train.txt", header = FALSE)
trainSubject <- read.table("./UCI HAR Dataset/train/subject_train.txt", header = FALSE)
trainFeatures <- read.table("./UCI HAR Dataset/train/X_train.txt", header = FALSE)
```

+ Binding "Test" and "Train" datasets in a "Data" dataset.
```
dataActivity <- rbind(trainActivity, testActivity)
dataSubject <- rbind(trainSubject, testSubject)
dataFeatures <- rbind(trainFeatures, testFeatures)
```

+ Reading "Features" and "Activity Labels" files and load in datasets.
```
features <- read.table("././UCI HAR Dataset/features.txt")
labelsActivity <- read.table("./UCI HAR Dataset/activity_labels.txt", header = FALSE)
```

##### 1.1 Setting variable names.
###### Set variables (column names) to "Subject", "Activity" and "Features" datasets.
```
names(dataSubject) <- c("Subject")
names(dataActivity) <- c("Activity")
names(dataFeatures) <- features$V2
```

##### 1.2  Binding datasets
###### Create a dataset for to bind "Subject", "Activity" datasets and create a new dataset to bing "Features" in "Subject" + "Activity" dataset.
```
data_Subj_Acti <- cbind(dataSubject, dataActivity)
data_Feat_Subj_Acti <- cbind(dataFeatures, data_Subj_Acti)
```

#### 2. Extracts only the measurements on the mean and standard deviation for each measurement.
###### Create a dataset for only the measurements on the mean and standard deviation for each measurement finding in "data_Feat_Subj_Acti" dataset.
```
dataMeanStd <- c(grep(".*Mean.*|.*Std.*", names(data_Feat_Subj_Acti), ignore.case=TRUE, value = TRUE),"Subject","Activity")
subset_one <- subset(data_Feat_Subj_Acti,select=colnames(data_Feat_Subj_Acti) %in% dataMeanStd)
```

#### 3. Uses descriptive activity names to name the activities in the data set
###### Data on activities dataset are numbers, but labels are more descritives than numbers. So, change numbers for labels activities.
```
subset_one$Activity <- factor(subset_one$Activity,labels = labelsActivity$V2)
```

#### 4. Appropriately labels the data set with descriptive variable names.
###### Column names had some acronyms and descriptive variable names are more easy to read. 
```
names(subset_one) <- gsub("tB", "timeB", names(subset_one))
names(subset_one) <- gsub("^t", "time", names(subset_one))
names(subset_one) <- gsub("^f", "frequency", names(subset_one))
names(subset_one) <- gsub("*std", "StandardDeviation", names(subset_one))
names(subset_one) <- gsub("*Freq", "Frequency", names(subset_one))
names(subset_one) <- gsub("*Acc", "Accelerometer", names(subset_one))
names(subset_one) <- gsub("*Gyro", "Gyroscope", names(subset_one))
names(subset_one) <- gsub("*Mag", "Magnitude", names(subset_one))
names(subset_one) <- gsub("*BodyBody", "Body", names(subset_one))   
```

#### 5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
###### Create a txt file after create a new subset with average of each variable for each activity and each subject.
```
subset_two <- aggregate(. ~Subject + Activity, subset_one, mean)
write.table(subset_two, file = "average_activity_subject.txt",row.names=FALSE)
```